name: Deploy docs (from master)

on:
  push:
    branches:
      - master
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Save SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.DEPLOY_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan mainnet.cash >> ~/.ssh/known_hosts
        shell: bash
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow
      - name: Push to rest-unstable
        run: |
          git branch
          git remote add dokku dokku@mainnet.cash:mainnet.cash
          git push -f dokku master
        shell: bash